#!/usr/bin/env bash

source $(dirname "$0")/game_p4.sh
for i in {1..7}; do
	eval c$i=0
done
for i in {1..100000}; do
	weighted_selection
	#eval c$?=$((\$c$?+1))
	
	case $? in
		1)((c1+=1));;
		2)((c2+=1));;
		3)((c3+=1));;
		4)((c4+=1));;
		5)((c5+=1));;
		6)((c6+=1));;
		7)((c7+=1));;
			*);;
		esac
done

for i in {1..7}; do
	eval echo "c$i = \$c$i"
done
