#!/usr/bin/env bash

source $(dirname "$0")/game_p4.sh

echo test weighted selection

for i in {1..7}; do
	eval c$i=0
done
for i in {1..1000}; do
	weighted_selection
	#eval c$?=$((\$c$?+1))
	
	case $? in
		1)((c1+=1));;
		2)((c2+=1));;
		3)((c3+=1));;
		4)((c4+=1));;
		5)((c5+=1));;
		6)((c6+=1));;
		7)((c7+=1));;
			*);;
		esac
done

for i in {1..7}; do
	eval echo "c$i = \$c$i"
done


echo test do while
test1=0
i=0
cond=true
while $cond || [ $test1 -eq 1 ]; do
	echo $cond
	cond=false
	if [ $i -lt 20 ]; then 
		test1=1 
		echo "lt 20"
	else
		test1=0
	fi
	((i++))
	echo "i: $i test: $test1"
done

list1=(1 2 3 4 5 6 7)
list2=(5 2 6)
echo "list1: ${list1[@]} list2: ${list2[@]}"
arr=($({ printf '%s\n' "${list1[@]}" "${list2[@]}"; } | sort | uniq -u))
echo "list: ${arr[@]}"
echo "fin"

